# Generated by Django 2.2.1 on 2019-05-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='MerchCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.AddField(
            model_name='merch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merch.MerchCategory'),
        ),
    ]
