# Generated by Django 2.2.1 on 2019-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20190517_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchcategory',
            name='description',
            field=models.CharField(default='desc', max_length=255),
            preserve_default=False,
        ),
    ]
