# Generated by Django 2.2.1 on 2019-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_merchcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchcategory',
            name='image',
            field=models.CharField(default='https://images.www.fendi.com/images/h09/hf6/8909664321566/8BT298A5DYF13QG_01_large', max_length=999),
            preserve_default=False,
        ),
    ]
