# Generated by Django 2.2.1 on 2019-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_merchcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='image',
            field=models.CharField(default='', max_length=999),
            preserve_default=False,
        ),
    ]
