# Generated by Django 2.2.1 on 2019-05-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
