# Generated by Django 2.2.1 on 2019-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='size',
            field=models.CharField(default=100, max_length=255),
            preserve_default=False,
        ),
    ]
