# Generated by Django 2.2.1 on 2019-05-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20190510_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='postal_code',
            field=models.IntegerField(default=101, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
