# Generated by Django 2.2.1 on 2019-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20190516_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefilter',
            name='order',
            field=models.CharField(blank=True, choices=[('name', 'Name lowest to highest'), ('-name', 'Name highest to lowest'), ('price', 'Price lowest to highest'), ('-price', 'Price highest to lowest'), ('size', 'Size lowest to highest'), ('-size', 'Size highest to lowest')], default='name', max_length=30),
        ),
    ]
